version: "3.7"
services:

    database:
        container_name: gamehub-db
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - ".mysql:/var/lib/mysql"
            - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: tps

    server:
        container_name: gamehub-server
        image: ubuntu:latest
